---
developers: []

domains:
  - erp-dev1.somcomunitats.coop

# Let's Encrypt conf
certificate_authority_email: "info@coopdevs.org"

# Set 'development_environment' to "True" to skip SSL and nginx tasks
development_environment: False

# Proxy and binding settings
odoo_role_odoo_http_interface: "127.0.0.1"
odoo_role_odoo_proxy_mode: True

# Change default SSH port
security_ssh_port: 2200

monitoring_enabled: False
backups_role_enabled: False
security_enabled: False

# Sentry
odoo_role_enable_sentry: False

odoo_role_test_dbs: ["odoo"]

# Queue Jobs
odoo_role_enable_queue_job: True
odoo_role_channels: "root:4"

# Workers
odoo_role_workers: 4

odoo_role_odoo_project_packages:
    - git+https://git.coopdevs.org/coopdevs/comunitats-energetiques/odoo-ce@dev#egg=odoo14-addon-energy-communities&subdirectory=setup/energy_communities
