---
# Use python3 interpreter
ansible_python_interpreter: "/usr/bin/python3"

firewall_enabled: False
security_enabled: False
# Odoo vars
odoo_role_odoo_user: odoo
odoo_role_odoo_dbs: [odoo]

odoo_role_download_strategy: tar
odoo_role_odoo_version: "14.0"
odoo_role_odoo_release: "14.0_2023-02-16"
odoo_role_odoo_url: "https://git.coopdevs.org/coopdevs/odoo/OCB/-/archive/{{ odoo_role_odoo_release }}/OCB-{{ odoo_role_odoo_release }}.tar.gz"
odoo_role_odoo_core_modules_dict:
  shared:
    - base
    - account_cancel
    - base_address_city
    - base_automation
    - base_vat
    - contacts
    - l10n_es
    - partner_autocomplete
    - purchase
    - mass_mailing
    - mass_mailing_crm
    - crm
    - web
    - base_sparse_field
    - queue_job

odoo_role_odoo_community_modules_dict:
  shared:  
    - account_asset_management
    - account_banking_mandate
    - account_banking_pain_base
    - account_banking_sepa_credit_transfer
    - account_banking_sepa_direct_debit
    - account_due_list
    - account_financial_report
    - account_fiscal_year
    - account_payment_mode
    - account_payment_order
    - account_payment_partner
    - account_payment_return
    - account_payment_return_import
    - account_payment_return_import_iso20022
    - account_payment_sale
    - account_statement_import_txt_xlsx
    - account_tax_balance
    - account_menu
    - account_multicompany_easy_creation
    - auth_oidc
    - base_bank_from_iban
    - base_iso3166
    - base_location
    - base_location_geonames_import
    - base_technical_features
    - base_user_role
    - base_user_role_company
    - base_rest
    - base_rest_auth_api_key
    - contract
    - contract_payment_mode
    - contract_variable_quantity
    - cooperator
    - cooperator_website
    - date_range
    - energy_communities
    - energy_project
    - energy_project_energy_communities
    - energy_selfconsumption
    - energy_selfconsumption_cooperator
    - l10n_es_account_asset
    - l10n_es_account_bank_statement_import_n43
    - l10n_es_account_banking_sepa_fsdd
    - l10n_es_aeat
    - l10n_es_aeat_mod111
    - l10n_es_aeat_mod190
    - l10n_es_aeat_mod115
    - l10n_es_aeat_mod123
    - l10n_es_aeat_mod303
    - l10n_es_aeat_mod390
    - l10n_es_aeat_mod347
    - l10n_es_facturae
    - l10n_es_irnr
    - l10n_es_mis_report
    - l10n_es_partner
    - l10n_es_partner_mercantil
    - l10n_es_toponyms
    - l10n_es_vat_book
    - l10n_es_cooperator
    - mail_tracking
    - mass_editing
    - mass_mailing_list_dynamic
    - mass_mailing_partner
    - mass_mailing_resend
    - mis_builder
    - mis_builder_budget
    - partner_firstname
    - report_py3o
    - report_xlsx
    - web_advanced_search
    - web_decimal_numpad_dot
    - web_environment_ribbon
    - web_no_bubble
    - web_responsive
    - web_timeline
    - web_widget_image_download

odoo_role_odoo_community_packages:
    - python-keycloak==2.9.0
    - python-slugify==8.0.1
    - odoo14-addon-account-asset-management==14.0.2.8.0
    - odoo14-addon-account-banking-mandate==14.0.1.2.0
    - odoo14-addon-account-banking-pain-base==14.0.1.0.2
    - odoo14-addon-account-banking-sepa-credit-transfer==14.0.1.2.1
    - odoo14-addon-account-banking-sepa-direct-debit==14.0.1.3.3
    - odoo14-addon-account-due-list==14.0.1.1.0
    - odoo14-addon-account-financial-report==14.0.3.4.1
    - odoo14-addon-account-fiscal-year==14.0.1.2.0
    - odoo14-addon-account-payment-mode==14.0.1.1.0
    - odoo14-addon-account-payment-order==14.0.1.11.0
    - odoo14-addon-account-payment-partner==14.0.1.7.0
    - odoo14-addon-account-payment-return==14.0.1.0.5
    - odoo14-addon-account-payment-return-import==14.0.1.0.3.dev1
    - odoo14-addon-account-payment-return-import-iso20022==14.0.1.0.1.dev2
    - odoo14-addon-account-payment-sale==14.0.1.0.1.dev14
    - odoo14-addon-account-tax-balance==14.0.1.2.6
    - odoo14-addon-account-menu==14.0.1.1.2.dev5
    - odoo14-addon-account-multicompany-easy-creation==14.0.1.0.1.dev2
    - odoo14-addon-base-bank-from-iban==14.0.1.0.2.dev3
    - odoo14-addon-base-iso3166==14.0.1.0.2.dev1
    - odoo14-addon-base-location==14.0.1.2.5.dev6
    - odoo14-addon-base-location-geonames-import==14.0.1.0.3.dev2
    - odoo14-addon-base-technical-features==14.0.1.1.2.dev1
    - odoo14-addon-base-user-role==14.0.2.5.1
    - odoo14-addon-base-user-role-company==14.0.2.0.1
    - odoo14-addon-base-rest==14.0.4.8.1
    - odoo14-addon-base-rest-auth-api-key==14.0.1.0.2
    - odoo14-addon-contract==14.0.2.9.4.dev2
    - odoo14-addon-contract-payment-mode==14.0.1.1.1
    - odoo14-addon-contract-variable-quantity==14.0.1.0.1.dev5
    - odoo14-addon-date-range==14.0.2.1.2.dev3
    - odoo14-addon-l10n-es-account-asset==14.0.1.0.1.dev6
    - odoo14-addon-l10n-es-account-statement-import-n43==14.0.1.0.4
    - odoo14-addon-l10n-es-account-banking-sepa-fsdd==14.0.1.0.1.dev5
    - odoo14-addon-l10n-es-aeat==14.0.2.4.5
    - odoo14-addon-l10n-es-aeat-mod111==14.0.2.0.0
    - odoo14-addon-l10n-es-aeat-mod190==14.0.1.0.1.dev3
    - odoo14-addon-l10n-es-aeat-mod115==14.0.1.0.1
    - odoo14-addon-l10n-es-aeat-mod123==14.0.1.0.1.dev5
    - odoo14-addon-l10n-es-aeat-mod303==14.0.3.5.0
    - odoo14-addon-l10n-es-aeat-mod390==14.0.3.1.0
    - odoo14-addon-l10n-es-aeat-mod347==14.0.2.2.0
    - odoo14-addon-l10n-es-facturae==14.0.2.5.0
    - odoo14-addon-l10n-es-irnr==14.0.1.0.1
    - odoo14-addon-l10n-es-mis-report==14.0.1.3.2.dev1
    - odoo14-addon-l10n-es-partner==14.0.1.0.3.dev1
    - odoo14-addon-l10n-es-partner-mercantil==14.0.1.0.1.dev4
    - odoo14-addon-l10n-es-toponyms==14.0.1.0.1.dev4
    - odoo14-addon-l10n-es-vat-book==14.0.2.4.1.dev1
    - odoo14-addon-mail-tracking==14.0.2.0.4.dev1
    - odoo14-addon-mass-editing==14.0.1.1.2
    - odoo14-addon-mis-builder==14.0.4.1.2.dev2
    - odoo14-addon-mis-builder-budget==14.0.4.0.2.dev5
    - odoo14-addon-partner-firstname==14.0.1.1.1.dev4
    - odoo14-addon-report-py3o==14.0.1.0.3
    - odoo14-addon-report-xlsx==14.0.1.0.10
    - odoo14-addon-web-advanced-search==14.0.1.0.2.dev3
    - odoo14-addon-web-decimal-numpad-dot==14.0.1.0.1.dev2
    - odoo14-addon-web-environment-ribbon==14.0.1.0.1.dev8
    - odoo14-addon-web-no-bubble==14.0.1.0.1.dev3
    - odoo14-addon-web-responsive==14.0.1.2.1.dev12
    - odoo14-addon-web-timeline==14.0.2.0.1.dev1
    - odoo14-addon-web-widget-image-download==14.0.1.0.1.dev4
    - odoo14-addon-auth-oidc==14.0.1.0.3.dev1
    - odoo14-addon-mass-mailing-list-dynamic==14.0.1.0.1.dev4
    - odoo14-addon-cooperator==14.0.1.5.2
    - odoo14-addon-cooperator-website==14.0.1.1.1
    - # This only works in pip install git+https://github.com/DaniilDigtyar/cooperative@14.0-ADD-l10n-es-cooperator#egg=odoo14-addon-l10n-es-cooperator\&subdirectory=setup/l10n_es_cooperator
    - git+https://github.com/DaniilDigtyar/cooperative@14.0-ADD-l10n-es-cooperator#egg=odoo14-addon-l10n-es-cooperator&subdirectory=setup/l10n_es_cooperator
    - git+https://github.com/OCA/bank-statement-import@14.0#egg=odoo14-addon-account-statement-import-txt-xlsx&subdirectory=setup/account_statement_import_txt_xlsx

# Odoo provisioning
odoo_provisioning_version: "v0.7.20"

# Nginx configuration
nginx_configs:
  upstream:
    - upstream odoo { server 127.0.0.1:8069; }

## Inventory-level nginx_http_extra_params.
nginx_inv_extra_params:
  - log_format main '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'
  - log_format vhost_main '$server_name $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'

# Work-around to have enabled backups.
# Beware that this enables the web db manager. It's the same thing.
odoo_role_list_db: true

# Support for loading system-wide modules
odoo_role_odoo_server_wide_modules: ["base","web","base_sparse_field","queue_job"]


nginx_sites:
  odoo:
    - |
      listen 80;
      server_name {{ domains | default([inventory_hostname]) | join(' ') }};
      rewrite ^(.*)$ https://$host$1 permanent;
  odoo.ssl:
    - |
      listen 443 ssl;
      ssl_certificate /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem;
      include /etc/letsencrypt/options-ssl-nginx.conf;
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
      server_name {{ domains | default([inventory_hostname]) | join(' ') }};
      proxy_read_timeout 720s;
      proxy_connect_timeout 720s;
      proxy_send_timeout 720s;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      underscores_in_headers on;
      access_log /var/log/nginx/odoo.access.log;
      error_log /var/log/nginx/odoo.error.log;
      location / {
        proxy_redirect off;
        proxy_pass http://odoo;
      }
      location /longpolling/ {
        proxy_pass http://127.0.0.1:8072;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
      }
      gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
      gzip on;
