---
# Use python3 interpreter
ansible_python_interpreter: "/usr/bin/python3"

# Venv vars
odoo_role_python_version: "3.8.18"
odoo_role_venv_name: "odoo"
odoo_role_odoo_venv_path: "/home/{{ odoo_role_odoo_user }}/pyenv/versions/{{ odoo_role_venv_name }}/"
odoo_role_pip_version: "23.0.1"

firewall_enabled: False
security_enabled: False

# Odoo vars
odoo_role_odoo_user: odoo
odoo_role_odoo_dbs: [odoo]

odoo_role_download_strategy: tar
odoo_role_odoo_version: "14.0"
odoo_role_odoo_release: "14.0_2023-02-16"
odoo_role_odoo_url: "https://git.coopdevs.org/coopdevs/odoo/OCB/-/archive/{{ odoo_role_odoo_release }}/OCB-{{ odoo_role_odoo_release }}.tar.gz"
odoo_role_odoo_core_modules_dict:
  shared:
    - account_cancel
    - base
    - base_address_city
    - base_automation
    - base_sparse_field
    - base_vat
    - contacts
    - crm
    - event
    - l10n_es
    - mass_mailing
    - mass_mailing_crm
    - partner_autocomplete
    - purchase
    - queue_job
    - web
    - website_event

odoo_role_odoo_community_modules_dict:
  shared:
    - account_asset_management
    - account_banking_pain_base
    - account_banking_sepa_credit_transfer
    - account_chart_update
    - account_due_list
    - account_financial_report
    - account_fiscal_year
    - account_menu
    - account_payment_mode
    - account_payment_return
    - account_payment_return_import
    - account_payment_return_import_iso20022
    - account_payment_sale
    - account_statement_import_txt_xlsx
    - account_tax_balance
    - base_bank_from_iban
    - base_future_response
    - base_iso3166
    - base_location
    - base_location_geonames_import
    - base_rest_auth_api_key
    - contract_payment_mode
    - cooperator_website
    - date_range
    - energy_communities
    - energy_communities_crm
    - energy_communities_cooperator
    - energy_communities_mass_mailing
    - energy_project
    - energy_project_energy_communities
    - energy_selfconsumption
    - energy_selfconsumption_cooperator
    - l10n_es_account_asset
    - l10n_es_account_bank_statement_import_n43
    - l10n_es_account_banking_sepa_fsdd
    - l10n_es_aeat
    - l10n_es_aeat_mod111
    - l10n_es_aeat_mod115
    - l10n_es_aeat_mod123
    - l10n_es_aeat_mod190
    - l10n_es_aeat_mod303
    - l10n_es_aeat_mod347
    - l10n_es_aeat_mod390
    - l10n_es_facturae
    - l10n_es_irnr
    - l10n_es_mis_report
    - l10n_es_partner
    - l10n_es_partner_mercantil
    - l10n_es_toponyms
    - l10n_es_vat_book
    - mail_tracking
    - mass_editing
    - mass_mailing_list_dynamic
    - mass_mailing_partner
    - mass_mailing_resend
    - mis_builder
    - mis_builder_budget
    - partner_contact_access_link
    - report_py3o
    - report_xlsx
    - web_access_rule_buttons
    - web_advanced_search
    - web_decimal_numpad_dot
    - web_environment_ribbon
    - web_no_bubble
    - web_responsive
    - web_timeline
    - web_widget_image_download

# Odoo provisioning
odoo_provisioning_version: "v0.7.21"

# Nginx configuration
nginx_configs:
  upstream:
    - upstream odoo { server 127.0.0.1:8069; }

## Inventory-level nginx_http_extra_params.
nginx_inv_extra_params:
  - log_format main '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'
  - log_format vhost_main '$server_name $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'

# Work-around to have enabled backups.
# Beware that this enables the web db manager. It's the same thing.
odoo_role_list_db: true

# Support for loading system-wide modules
odoo_role_odoo_server_wide_modules: ["base","base_future_response","web","base_sparse_field","queue_job"]


nginx_sites:
  odoo:
    - |
      listen 80;
      server_name {{ domains | default([inventory_hostname]) | join(' ') }};
      rewrite ^(.*)$ https://$host$1 permanent;
  odoo.ssl:
    - |
      listen 443 ssl;
      ssl_certificate /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem;
      include /etc/letsencrypt/options-ssl-nginx.conf;
      ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
      server_name {{ domains | default([inventory_hostname]) | join(' ') }};
      proxy_read_timeout 720s;
      proxy_connect_timeout 720s;
      proxy_send_timeout 720s;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      underscores_in_headers on;
      access_log /var/log/nginx/odoo.access.log;
      error_log /var/log/nginx/odoo.error.log;
      location / {
        proxy_redirect off;
        proxy_pass http://odoo;
      }
      location /longpolling/ {
        proxy_pass http://127.0.0.1:8072;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
      }
      gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
      gzip on;
